### ISSUE TITLE
Why is this nascent?

### ISSUE THREAD

**Issue by nkrth** [ghewgill/soirc#1]
I'm not sure what that word means but this project means a lot to me because it's on SO's FAQ.
Hope you guys don't leave it idle.
~nix [22/12/2018]

**Comment by ghewgill** [comment]
"Nascent" means it was the start of something, but it's been idle for years. No plans to resume development.

**Comment by kopax** [comment]
Hi, is there still a way to use IRC to connect to stackoverflow chat? Also I don't see why they didn't use the IRC protocole at the beggning, this seems like an odd choice. Every features they added could be added on top. SO justification is that they try to do better than IRC, but that is not actually the case.
